# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Mark's Blog
tagline:             
description:         'Hello and welcome to my blog! My name is Mark Stockdale and I'm currently attending a coding bootcamp with Awesome Inc., located in Lexington, KY. I've worked in healthcare for years, but a couple of months ago, I finally decided to change course and pursue becoming a web developer. I've always loved working with computers and technology and decided it was time to start aligning my career path with my passions.'
url:                 https://stockdalemark1978.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Stockdale
  url:               https://stockdalemark1978.github.io/
  email:             stockdalemark1978@gmail.com

# Custom vars
version:             1.0.0
